language: node_js
dist: trusty
node_js:
  - 7
  - 6
script:
  - node --version
  - npm --version
  - npm test
notifications:
  email:
    on_failure: change
cache:
  bundler: true
  directories:
    - node_modules
deploy:
  provider: npm
  email: romellogood@gmail.com
  api_key:
    secure: peR/5Ga9s6c/u1wPptsPTRvMskcv7HAwK8Df0Nz7DE9HBfgDBuZIxMlmkbcMihe5JvPEhE5nYfkmRxo0it6nwk1dxSETDCrW7fMaYkT4fBcLY6jN2/qoRomF4noGCs8RtpY70QnPWJXec16AVJTMN6ErcZjd7mJOL5rHErTjx2Tc2T4/VxKz+v4OUNwrEpKXHZDO2IQeXvyRSBdJBdcQPf0iOD0veOO1CjvSD0nrFLEtSARXejhA9Elkm/zqNZojqqD3bGd6Dh/R7Cq3XQeLlP6CgiDFo7ahvKiDO6Djcb3t82MviGaB4EDtdO9WRDgTWnKnE+M4aF/8oTnRoKPLLLoEY37Nd3mtTv9GDe7C81I5r3XO8/TYnkSC8lJQKgfZw3KeKVUZ172r+nz8Syiuo56OTm9gP9P87hN0cvRmJIruj+jkb3buEU+vo2vtlTAr4emWIWgriU2fjR0KzzBgYt9dAxybqztOcCtWoWn4huhPSaZfSMZPu0FKKNib+ko7wgCNTZ4Lk87yUGHFw1tPnLZKBN0iARzCk2ZKlcYLmaGBnBv2Rps8m2EuJIGzw66T8RgKKqmyMGAGgLr2ryWs0D9vlpzftzTfrOSd6T56+7zmARPey0NJRCM0Mhlt3/RtAf5xuLJF6gfLQ9HhH80f0kMM2jE2bZvTT3AB+KMxeF0=
  on:
    tags: true
    repo: romellogood/react-csv-creator
